name: Deploy to Swarm

on:
  workflow_run:
    workflows: [ "Image Build & Push QS Off Site" ]
    types: [ completed ]
    branches: [ main ]

  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    uses: QuackStack-LTD/Pond/.github/workflows/swarm-deploy.yaml@main
    with:
      stack: deployment
      compose-file: docker-stack.yaml
      images-csv: ghcr.io/os-tues/os-tues-hacktues-prep-2026:latest
      clean-volumes: true
      
      docker-api-version: "1.47"
      readiness-attempts: 12
      readiness-sleep-seconds: 10
    secrets:
      SWARM_MANAGER_IP:      ${{ secrets.SWARM_MANAGER_IP_HOSTINGER }}
      SWARM_CA_PEM:          ${{ secrets.SWARM_CA_PEM_HOSTINGER }}
      SWARM_CLIENT_CERT_PEM: ${{ secrets.SWARM_CLIENT_CERT_PEM_HOSTINGER }}
      SWARM_CLIENT_KEY_PEM:  ${{ secrets.SWARM_CLIENT_KEY_PEM_HOSTINGER }}
